WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET VERIFY OFF;
DEFINE FLINK_CDC_PASSWORD = '&1';

ALTER SYSTEM SET db_recovery_file_dest_size = 10G SCOPE=BOTH;
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

DECLARE
  user_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_count FROM dba_users WHERE username = 'C##FLINK';
  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER C##FLINK IDENTIFIED BY "&&FLINK_CDC_PASSWORD" CONTAINER=ALL';
  END IF;
END;
/

ALTER USER C##FLINK QUOTA UNLIMITED ON USERS CONTAINER=ALL;
GRANT CREATE SESSION TO C##FLINK CONTAINER=ALL;
GRANT SET CONTAINER TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##FLINK CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO C##FLINK CONTAINER=ALL;
GRANT CREATE TABLE TO C##FLINK CONTAINER=ALL;
GRANT LOCK ANY TABLE TO C##FLINK CONTAINER=ALL;
GRANT CREATE SEQUENCE TO C##FLINK CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##FLINK CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##FLINK CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##FLINK CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##FLINK CONTAINER=ALL;
GRANT LOGMINING TO C##FLINK CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO C##FLINK CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##FLINK CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##FLINK CONTAINER=ALL;

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE APPUSER.RT (
  SCANINDEX NUMBER PRIMARY KEY,
  FILENAME  VARCHAR2(255),
  FILEPATH  VARCHAR2(1000),
  COL01     VARCHAR2(255),
  COL02     VARCHAR2(255)
);

CREATE TABLE APPUSER.DWAF_HIS (
    SCANINDEX     NUMBER NOT NULL,
  SUBLOT_ID     VARCHAR2(255),
  WAF_ID        VARCHAR2(255),
  DATA_CHG_DTTM VARCHAR2(64)
);

ALTER TABLE APPUSER.DWAF_HIS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE APPUSER.RT ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO APPUSER.RT (SCANINDEX, FILENAME, FILEPATH, COL01, COL02)
VALUES (1001, 'wafer-1001.tif', '/data/images/lot-a', 'demo-1', 'demo-2');
COMMIT;

SELECT LOG_MODE FROM V_$DATABASE;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES
WHERE OWNER = 'APPUSER' AND TABLE_NAME IN ('RT', 'DWAF_HIS')
ORDER BY TABLE_NAME;

EXIT;
