WHENEVER SQLERROR EXIT SQL.SQLCODE;
DELETE FROM APPUSER.DWAF_HIS WHERE SCANINDEX = 1001;

INSERT INTO APPUSER.DWAF_HIS (SCANINDEX, SUBLOT_ID, WAF_ID, DATA_CHG_DTTM)
VALUES (1001, 'SUBLOT-A', 'WAF-001', TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS.FF3'));
COMMIT;
EXIT;
